---
- name: Create Users and Assign random password
  hosts: all
  become: true
  vars_files:
    - users.yml
  tasks:
  - name: User module
    vars:
      password: "{{ lookup('password', '' '/tmp/{{ item.name }}-password.txt' ' length=6') }}"
    user:
      name: "{{ item.name }}"
      uid: "{{ item.uid }}"
      comment: "{{ item.first|capitalize }} {{ item.last|capitalize }} {{item.middle|capitalize }}"
      shell: /bin/bash
      password: "{{ password|password_hash('sha256') }}"
      update_password: on_create
      state: present
    with_items: "{{ myusers }}"  
